changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - github-actions
      - app/dependabot
  categories:
    - title: Breaking Changes 🔔
      labels:
        - semver-major
    - title: Features 🎉
      labels:
        - kind/feat
    - title: Fixes 🛠
      labels:
        - kind/fix
    - title: Operations ♻️
      labels:
        - kind/chore
    - title: Other Changes
      labels:
        - "*"
