# permissions for end users to view cidrs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cidr-viewer-role
rules:
- apiGroups:
  - net.cogadvisor.io.net.cogadvisor.io
  resources:
  - cidrs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - net.cogadvisor.io.net.cogadvisor.io
  resources:
  - cidrs/status
  verbs:
  - get
