# permissions for end users to edit cidrs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cidr-editor-role
rules:
- apiGroups:
  - net.cogadvisor.io.net.cogadvisor.io
  resources:
  - cidrs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - net.cogadvisor.io.net.cogadvisor.io
  resources:
  - cidrs/status
  verbs:
  - get
