# permissions for end users to edit cniconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cniconfig-editor-role
rules:
- apiGroups:
  - net.cogadvisor.io.net.cogadvisor.io
  resources:
  - cniconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - net.cogadvisor.io.net.cogadvisor.io
  resources:
  - cniconfigs/status
  verbs:
  - get
