# permissions for end users to edit configs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: config-editor-role
rules:
- apiGroups:
  - multinic.fms.io.multinic.fms.io
  resources:
  - configs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - multinic.fms.io.multinic.fms.io
  resources:
  - configs/status
  verbs:
  - get
