# permissions for end users to edit deviceclasses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deviceclass-editor-role
rules:
- apiGroups:
  - net.cogadvisor.io
  resources:
  - deviceclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - net.cogadvisor.io
  resources:
  - deviceclasses/status
  verbs:
  - get
