# permissions for end users to view deviceclasses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deviceclass-viewer-role
rules:
- apiGroups:
  - net.cogadvisor.io
  resources:
  - deviceclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - net.cogadvisor.io
  resources:
  - deviceclasses/status
  verbs:
  - get
