# permissions for end users to view hostinterfaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hostinterface-viewer-role
rules:
- apiGroups:
  - net.cogadvisor.io.net.cogadvisor.io
  resources:
  - hostinterfaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - net.cogadvisor.io.net.cogadvisor.io
  resources:
  - hostinterfaces/status
  verbs:
  - get
