# permissions for end users to view ippools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ippool-viewer-role
rules:
- apiGroups:
  - net.cogadvisor.io.net.cogadvisor.io
  resources:
  - ippools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - net.cogadvisor.io.net.cogadvisor.io
  resources:
  - ippools/status
  verbs:
  - get
