apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: multi-nic-cni-k8s-binding
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: system
roleRef:
  kind: ClusterRole
  name: multi-nic-cni-k8s
  apiGroup: rbac.authorization.k8s.io