apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: multi-nic-cni-k8s
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  - namespaces
  verbs:
  - get
  - watch
  - list
  - patch
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch