# permissions for end users to edit multinicnetworks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: multinicnetwork-editor-role
rules:
- apiGroups:
  - net.cogadvisor.io
  resources:
  - multinicnetworks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - net.cogadvisor.io
  resources:
  - multinicnetworks/status
  verbs:
  - get
