# permissions for end users to view multinicnetworks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: multinicnetwork-viewer-role
rules:
- apiGroups:
  - multinic.fms.io
  resources:
  - multinicnetworks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - multinic.fms.io
  resources:
  - multinicnetworks/status
  verbs:
  - get
