apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: multi-nic-cni-netattachdef
rules:
- apiGroups:
  - k8s.cni.cncf.io
  resources:
  - network-attachment-definitions
  verbs:
  - create
  - update
  - get
  - watch
  - list
  - delete