apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: multi-nic-cni-privileged-cr-binding
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: system
roleRef:
  kind: ClusterRole
  name: privileged-cr
  apiGroup: rbac.authorization.k8s.io