apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-nic-cni-health-checker
  namespace: multi-nic-cni-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      multi-nic-cni-component: health-checker
  template:
    metadata:
      labels:
        multi-nic-cni-component: health-checker
      annotations:
        k8s.v1.cni.cncf.io/networks: netname
    spec:
      serviceAccount: multi-nic-cni-health-checker-sa
      serviceAccountName: multi-nic-cni-health-checker-sa
      containers:
        - name: checker
          image: ghcr.io/foundation-model-stack/multi-nic-cni-health-checker:v1.0.5
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: CHECKER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: CHECKER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: TARGET_NETWORK
              valueFrom:
                  fieldRef:
                    fieldPath: metadata.annotations['k8s.v1.cni.cncf.io/networks']