## Append samples you want in your CSV to this file as resources ##
resources:
- multinic.fms.io_multinicnetwork.yaml
- multinic.fms.io_deviceclass.yaml
- multinic.fms.io_config.yaml
- multinic.fms.io_hostinterface.yaml
- multinic.fms.io_cidr.yaml
- multinic.fms.io_ippool.yaml
#+kubebuilder:scaffold:manifestskustomizesamples

configurations:
- kustomizeconfig.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: multi-nic-cni-daemon
  newName: ghcr.io/foundation-model-stack/multi-nic-cni-daemon
  newTag: v1.2.4
