## Append samples you want in your CSV to this file as resources ##
resources:
- multinic.fms.io_v1_config.yaml
- net_v1_deviceclass.yaml
- net_v1_multinicnetwork.yaml
#+kubebuilder:scaffold:manifestskustomizesamples

configurations:
- kustomizeconfig.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: multi-nic-cni-daemon
  newName: ghcr.io/foundation-model-stack/multi-nic-cni-daemon
  newTag: v1.0.0
