apiVersion: multinic.fms.io/v1
kind: MultiNicNetwork
metadata:
  name: multinic-aws-ipvlan
spec:
  ipam: |
    {
      "type": "multi-nic-ipam",
      "hostBlock": 8, 
      "interfaceBlock": 2,
      "vlanMode": "l2"
    }
  multiNICIPAM: true
  plugin:
    cniVersion: "0.3.0"
    type: aws-ipvlan
    args: 
      mode: l2
  namespaces:
  - default