apiVersion: net.cogadvisor.io/v1
kind: MultiNicNetwork
metadata:
  name: multinic-ipvlanl2
  namespace: default
spec:
  subnet: "172.31.49.0/24"
  ipam: |
    { "type": "whereabouts" }
  multiNICIPAM: false
  plugin:
    cniVersion: "0.3.0"
    type: ipvlan
    args: 
      mode: l2
  masterNets:
    - "172.31.32.0/20"