apiVersion: v1
kind: ServiceAccount
metadata:
  name: multi-nic-cni-health-check-agent-sa
  namespace: multi-nic-cni-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: multi-nic-privileged-cr
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: multi-nic-cni-privileged-cr-binding
subjects:
- kind: ServiceAccount
  name: multi-nic-cni-health-check-agent-sa
  namespace: multi-nic-cni-operator
roleRef:
  kind: ClusterRole
  name: multi-nic-privileged-cr
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: multi-nic-cni-health-agent
  namespace: multi-nic-cni-operator
spec:
  selector:
    matchLabels:
      multi-nic-cni-component: health-check-agent
  template:
    metadata:
      labels:
        multi-nic-cni-component: health-check-agent
    spec:
      containers:
      - env:
        - name: SIDECAR_PORT
          value: "11001"
        - name: CNI_PATH
          value: /host/opt/cni/bin
        - name: K8S_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: K8S_POD_NAMESPACE
          valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
        image: ghcr.io/foundation-model-stack/multi-nic-cni-health-check-sidecar:v1.0.5
        imagePullPolicy: Always
        name: health-check-agent
        ports:
        - containerPort: 11001
          hostPort: 11001
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 200m
            memory: 100Mi
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /host/opt/cni/bin
          name: cnibin
      dnsPolicy: ClusterFirst
      hostNetwork: true
      serviceAccount: multi-nic-cni-health-check-agent-sa
      serviceAccountName: multi-nic-cni-health-check-agent-sa
      volumes:
      - hostPath:
          path: /var/lib/cni/bin
          type: ""
        name: cnibin