apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: multi-nicd
  namespace: multi-nic-cni-operator
spec:
  template:
    spec:
      containers:
      - name: multi-nicd
      - env:
        - name: SIDECAR_PORT
          value: "11001"
        - name: CNI_PATH
          value: /host/opt/cni/bin
        - name: K8S_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: K8S_POD_NAMESPACE
          valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
        image: ghcr.io/foundation-model-stack/multi-nic-cni-health-check-sidecar:v1.0.3
        imagePullPolicy: Always
        name: health-check-agent
        ports:
        - containerPort: 11001
          hostPort: 11001
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /host/opt/cni/bin
          name: cnibin