FROM ghcr.io/foundation-model-stack/multi-nic-cni-kbuilder:v1.2.9

RUN  apt-get update \
  && apt-get install -y jq \
  && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /usr/local/app
RUN mkdir -p /host/opt/cni/bin

WORKDIR /usr/local/build
# build CNI
RUN mkdir -p cni
COPY cni/go.mod cni/go.mod
COPY cni/Makefile cni/Makefile
COPY cni/pkg cni/pkg
COPY cni/plugins/main/multi-nic cni/plugins/main/multi-nic
RUN cd cni && go mod tidy && go build -o /usr/local/app/multi-nic ./plugins/main/multi-nic
COPY cni/plugins/ipam cni/plugins/ipam
RUN cd cni && go mod tidy && go build -o /usr/local/app/multi-nic-ipam ./plugins/ipam/multi-nic-ipam
COPY cni/plugins/main/aws-ipvlan cni/plugins/main/aws-ipvlan
RUN cd cni && go mod tidy && go build -o /usr/local/app/aws-ipvlan ./plugins/main/aws-ipvlan
RUN cd cni && make ginkgo-set
# build Daemon
COPY daemon daemon
COPY hack daemon/hack
RUN mkdir -p /usr/local/kubebuilder
RUN mkdir -p /usr/local/build/daemon/src/test-bin
RUN cd daemon/src && go mod tidy
RUN cd daemon/src && go build -o /usr/local/app/daemon
RUN cp /usr/local/app/multi-nic /usr/local/bin \ 
&& cp /usr/local/app/multi-nic-ipam /usr/local/bin \
&& cp /usr/local/app/aws-ipvlan /usr/local/bin
WORKDIR /usr/local/app
COPY daemon/run.sh run.sh

CMD ["/bin/bash", "run.sh"]
