FROM --platform=linux/amd64 ghcr.io/foundation-model-stack/multi-nic-cni-kbuilder

RUN mkdir -p /usr/local/app
RUN mkdir -p /host/opt/cni/bin

WORKDIR /usr/local/build
COPY daemon daemon
RUN mkdir -p daemon/src/test-bin

RUN cd daemon/src && go mod tidy 
RUN mkdir -p cni
COPY cni/go.mod cni/go.mod
COPY cni/Makefile cni/Makefile
COPY cni/pkg cni/pkg
COPY cni/plugins/main/multi-nic cni/plugins/main/multi-nic
RUN cd cni && go mod tidy && go build -o /usr/local/app/multi-nic ./plugins/main/multi-nic
COPY cni/plugins/ipam cni/plugins/ipam
RUN cd cni && go mod tidy && go build -o /usr/local/app/multi-nic-ipam ./plugins/ipam/multi-nic-ipam
RUN cd cni && make ginkgo-set
RUN cd daemon/src && go build -o /usr/local/app/daemon
RUN cp /usr/local/app/multi-nic /usr/local/bin \ 
&& cp /usr/local/app/multi-nic-ipam /usr/local/bin
WORKDIR /usr/local/app
COPY daemon/run.sh run.sh

CMD ["/bin/bash", "run.sh"]