apiVersion: multinic.fms.io/v1
kind: MultiNicNetwork
metadata:
  name: multinic-macvlan
  namespace: default
spec:
  subnet: "192.168.0.0/16"
  ipam: |
    {
      "type": "whereabouts",
      "range": "192.168.0.0/16"
    }
  multiNICIPAM: false
  plugin:
    cniVersion: "0.3.1"
    type: macvlan
