apiVersion: multinic.fms.io/v1
kind: MultiNicNetwork
metadata:
  name: multinic-macvlan
  namespace: default
spec:
  subnet: "192.168.0.0/16"
  ipam: |
    {
      "type": "multi-nic-ipam",
      "hostBlock": 8, 
      "interfaceBlock": 2,
      "vlanMode": "l2"
    }
  multiNICIPAM: true
  plugin:
    cniVersion: "0.3.1"
    type: macvlan
    args: 
      mode: bridge
