apiVersion: multinic.fms.io/v1
kind: MultiNicNetwork
metadata:
  name: multinic-sriov
spec:
  subnet: "172.34.0.0/16"
  ipam: |
    {
      "type": "multi-nic-ipam",
      "hostBlock": 8,
      "interfaceBlock": 2,
      "vlanMode": "l2"
    }
  multiNICIPAM: true
  plugin:
    cniVersion: "0.3.0"
    type: sriov
    args:
      numVfs: "2"
      isRdma: "true"
