apiVersion: v1
kind: Namespace
metadata:
  name: multi-nic-cni
  labels:
    openshift.io/cluster-monitoring: "true"
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: CIDR.v1.multinic.fms.io,Config.v1.multinic.fms.io,DeviceClass.v1.multinic.fms.io,HostInterface.v1.multinic.fms.io,IPPool.v1.multinic.fms.io,MultiNicNetwork.v1.multinic.fms.io
  name: multi-nic-cni
  namespace: multi-nic-cni
spec:
  staticProvidedAPIs: true