name: PR build 

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - .github/workflows/build_push_pr.yaml
      - controllers/**
      - compute/**
      - plugin/**
      - ./main.go
      - ./go.mod
      - config/**
      - ./Dockerfile
      - ./bundle.Dockerfile
      - ./Makefile
      - daemon/**
      - cni/**

env:
  VERSION: pr-${{ github.event.pull_request.number }}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  DAEMON_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  build-push-controller:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository }}-controller
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.0'
      - name: Tidy
        run: |
          go mod tidy
          make generate fmt vet
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Build and push controller
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:v${{ env.VERSION }}
          file: ./Dockerfile

  build-push-daemon:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository }}-daemon
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.0'
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
      - name: Update CNI
        run: make update-cni-local
        working-directory: daemon
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Build and push daemon
        uses: docker/build-push-action@v2
        with:
          context: daemon
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:v${{ env.VERSION }}
          file: ./daemon/dockerfiles/Dockerfile
