name: Build and push daemon kbuilder image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'kbuilder image version'
        required: true

env:
  IMAGE_VERSION: "1.3.1"

jobs:
  build-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/multi-nic-cni-kbuilder
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.24.1'
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:v${{ env.IMAGE_VERSION }}
          file: ./daemon/dockerfiles/Dockerfile.kbuilder
