name: Build and push connection check image

on:
  push:
    branches:
      - v1.2.4
    paths:
      - connection-check/**

env:
  IMAGE_VERSION: '1.2.4'
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  build-push-concheck:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository }}-concheck
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.0'
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Build and push concheck
        uses: docker/build-push-action@v2
        with:
          context: connection-check
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:v${{ env.IMAGE_VERSION }}
          file: ./connection-check/Dockerfile