name: golangci-lint
on:
  pull_request:
  push:

env:
  GOLANGCI_LINT_VERSION: v1.64.8

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.24.1'
      - uses: actions/checkout@v3
      - name: Tidy
        run: |
          go mod tidy
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout=10m
          version: ${{ env.GOLANGCI_LINT_VERSION }}
