apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: ens1f0-policy
  namespace: openshift-sriov-network-operator
spec:
  resourceName: sriovens1f0
  nodeSelector:
    feature.node.kubernetes.io/network-sriov.capable: "true"
  numVfs: 4
  nicSelector:
    vendor: "15b3"
    deviceID: "1019"
    rootDevices: ["0000:1a:00.0"]